name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem  # Store the SSH private key
          chmod 600 private_key.pem  # Set proper permissions for the private key

      - name: Deploy to Server using SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 20.102.119.98  # The IP of your server
          username: measuremates-vm001  # Your server username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # The SSH private key stored in GitHub secrets
          port: 22  # The SSH port (default is 22)
          script: |
            cd ~/amora

            # Ensure Python 3.8 is installed
            sudo apt update
            sudo apt install -y python3.8 python3.8-venv python3.8-dev

            # Create virtual environment if not exists
            if [ ! -d "venv" ]; then
              python3.8 -m venv venv
            fi

            source venv/bin/activate  # Activate virtual environment

            # Ensure pip is up to date
            pip install --upgrade pip

            git pull origin main  # Pull latest changes

            pip install -r requirements.txt  # Install dependencies

            sudo systemctl daemon-reload  # Reload systemd
            sudo systemctl restart amora.service  # Restart application
            sudo systemctl status amora.service --no-pager --lines=50  # Show logs